import {StyleSheet} from 'react-native';
import Colors from '../../theme/Colors';

export default styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: Colors.primary,
  },
  mainHeading: {
    fontSize: 26,
    fontWeight: 'bold',
    color: Colors.lightslategray,
    textAlign: 'center',
    margin: 10,
    borderBottomColor: Colors.lightslategray,
    borderBottomWidth: 1,
    borderStyle: 'dashed',
    width: '70%',
    alignSelf: 'center',
  },
  productContainer: {
    height: 150,
    width: '90%',
    marginVertical: 20,
    backgroundColor: Colors.white,
    borderRadius: 10,
    flexDirection: 'row',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'space-around',
    elevation: 10,
  },
  insideContainerView1: {
    width: 120,
    height: 120,
    borderWidth: 1.5,
    borderColor: Colors.lightslategray,
    borderRadius: 10,
    marginLeft: 10,
  },
  insideContainerView2: {
    width: '60%',
    height: 120,
    // backgroundColor: Colors.lightslategray,
  },
  productName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: Colors.lightslategray,
    marginLeft: 5,
  },
  productDescription: {
    fontSize: 15,
    color: Colors.lightslategray,
    marginLeft: 5,
  },
  productPrice: {
    fontSize: 24,
    fontWeight: 'bold',
    color: Colors.blue,
    margin: 5,
  },
  productRatings: {color: 'black', fontSize: 20},
  addToCartButton: {
    width: '50%',
    height: 30,
    borderWidth: 1,
    borderRadius: 7,
    marginLeft: 5,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: 'black',
  },
  addToCartButtonTitle: {fontSize: 16, color: 'black'},
  quantityView: {
    flexDirection: 'row',
    width: '40%',
    marginLeft: 5,
    justifyContent: 'space-between',
  },
  quantityButton: {
    height: 25,
    width: 25,
    backgroundColor: Colors.primary,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'black',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantityButtonSymbols: {
    fontWeight: '500',
    fontSize: 20,
    textAlign: 'center',
    lineHeight: 25,
    color: 'black',
  },
  quantity: {fontSize: 20, color: 'black', fontWeight: '500'},
  bottomContainer: {
    backgroundColor: 'white',
    borderTopColor: 'black',
    borderTopWidth: 1,
    height: 100,
    width: '100%',
    position: 'absolute',
    bottom: 0,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  bottomInsideContainer1: {
    // alignItems: 'center',
    paddingLeft: 15,
    justifyContent: 'center',
    height: 80,
    // backgroundColor: 'pink',
    width: '55%',
  },
  bottomInsideContainer1Text: {
    fontSize: 18,
    color: 'black',
    fontWeight: '600',
    margin: 3,
  },
  bottomInsideContainer2: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 80,
    // backgroundColor: 'pink',
    width: '35%',
  },
  viewCartButton: {
    height: 40,
    width: '80%',
    backgroundColor: 'skyblue',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'black',
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewCartButtonTitle: {
    fontSize: 18,
    fontWeight: '700',
  },
});
